create table if not exists public.match_lineups (
  id bigint generated by default as identity primary key,
  match_id bigint not null
    references public."Matches"(id)
    on delete cascade,
  player_id uuid not null
    references public.players(id)
    on delete cascade,
  team text not null
    check (team in ('home', 'away')),
  status text not null
    check (status in ('starting', 'substitute', 'absent')),
  absence_reason text,
  created_at timestamptz not null default now(),
  unique(match_id, player_id)
);

alter table public.match_lineups enable row level security;

drop policy if exists "match_lineups_admin_all"
on public.match_lineups;

create policy "match_lineups_admin_all"
on public.match_lineups
for all
to authenticated
using (true)
with check (true);

create index if not exists idx_match_lineups_match_id
on public.match_lineups(match_id);

create index if not exists idx_match_lineups_player_id
on public.match_lineups(player_id);